Feature/cpo 36 main navigation
AmeXio-Contentful/poc-contentful-nextjs pull request #15
Opened 2024-05-08 07:55 UTC by Polleke007

2024-05-13 11:30 UTC, DavithkbY requested changes

2024-05-13 11:30 UTC, DavithkbY commented on src/components/features/ctf-components/ctf-navigation/ctf-navigation.tsx
> +  navigationContent?.menuItemsCollection?.items.forEach((item:any) => {
can we use typing here instead of any?

2024-05-13 11:48 UTC, ceneva approved these changes

2024-05-14 07:15 UTC, Polleke007 commented on src/components/features/ctf-components/ctf-navigation/ctf-navigation.tsx
> +          <ul className='flex flex-row items-center list-none capitalize m-0 p-0 '>
That's correct, the nav is 2 levels deep, sure it would be possible but for the home this is not needed

2024-05-15 06:05 UTC, DavithkbY approved these changes

2024-05-15 06:05 UTC, merged