added 2grid system
AmeXio-Contentful/poc-contentful-nextjs pull request #28
Opened 2024-05-24 14:31 UTC by Polleke007

2024-05-27 08:13 UTC, ceneva requested changes

2024-05-27 08:13 UTC, ceneva commented on src/mapping/sanity/expert-advice.tsx
> +import { Button } from '@src/components/features/decoupled-components/button/button';
In the mapping folder shouldn't be any component code, all data/query related code should go in folder data, all component code should be in folder component, the only thing that the mapping is supposed to do is to connect the sanity specific data to the generic component data it belongs to, it transfers (or slightly alters) the data wherever needed. Can you please split the code into the right parts? Thanks. Feel free to ask questions if needed ;-)

2024-05-27 08:13 UTC, ceneva commented on src/mapping/sanity/featured-article.tsx
> +import {PortableText} from '@portabletext/react'
Same comment as for expert advice

2024-05-27 08:13 UTC, ceneva commented on src/mapping/sanity/featured-article.tsx
> +  console.log("props", props);
Please remove console logs

2024-05-27 08:13 UTC, ceneva commented on src/mapping/sanity/two-grid.tsx
> +import React from 'react';
Same comment as for expert advice

2024-05-30 15:14 UTC, DavithkbY requested changes
Fix Celien's comments

2024-06-04 08:26 UTC, merged